[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
beryllium = "0.13.3"
bmp = "0.5.0"
bytemuck = "1.23.1"
gl33 = "0.2.1"
imagine = "0.5.3"
png = "0.17.16"
tobj = "4.0.3"
ultraviolet = "0.10.0"
